[general]
live_config_reload = true
import = [
  "C:\\Users\\keena\\AppData\\Roaming\\npm\\node_modules\\alacritty-themes\\themes\\Gruvbox-Dark.toml"
]

[terminal.shell]
program = "ubuntu.exe"

[env]
TERM = "alacritty"

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.9
blur = true

  [window.padding]
  x = 3
  y = 3

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 8
builtin_box_drawing = true

  [font.normal]
  family = "MesloLGS NF"
  style = "Regular"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "#181818"
background = "#ac4242"

[colors.search.focused_match]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.start]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.end]
foreground = "#181818"
background = "#ac4242"

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"

[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"

[bell]
animation = "Linear"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
unfocused_hollow = true
thickness = 0.15

  [cursor.style]
  shape = "Block"
  blinking = "Off"

[mouse]
hide_when_typing = false
